Fix 'cannot spawn .git/hooks/post-rewrite' on Windows
Following is happening:

'''
error: cannot spawn .git/hooks/post-rewrite: No such file or directory: No such file or directory
'''

because the first line of the stubbed post-rewrite is a new-line, which
is interpretted by mingw as "not a shell script".